
SAME_CHECKS = [['Pylon/Probe', 'SupplyDepot/SCV', 'SupplyDepotDrop/SCV'],
               ['Assimilator/Probe', 'Extractor/Drone', 'Refinery/SCV', 'AutomatedRefinery/SCV', 'AutomatedExtractor/Drone'],
               ['Gateway/Probe', 'Barracks/SCV'],
               ['Nexus/Probe', 'Hatchery/Drone', 'CommandCenter/SCV', 'CommandCenterOrbRelay/SCV'],
               ['Forge/Probe', 'EvolutionChamber/Drone', 'EngineeringBay/SCV'],
               ['RoboticsFacility/Probe', 'Factory/SCV'],
               ['Stargate/Probe', 'Spire/Drone', 'Starport/SCV'],
               ['TwilightCouncil/Probe', 'Armory/SCV'],
               ['FleetBeacon/Probe', 'FusionCore/SCV'],
               ['ProtossGroundWeaponsLevel1/Forge', 'TerranInfantryWeaponsLevel1/EngineeringBay', 'TerranInfantryWeaponsUltraCapacitorsLevel1/EngineeringBay', 'TerranInfantryWeaponsUltraCapacitorsLevel2/EngineeringBay', 'TerranInfantryWeaponsUltraCapacitorsLevel3/EngineeringBay'],
               ['ProtossGroundArmorLevel1/Forge', 'TerranInfantryArmorLevel1/EngineeringBay', 'zerggroundarmor1/EvolutionChamber', 'TerranInfantryArmorVanadiumPlatingLevel1/EngineeringBay', 'TerranInfantryArmorVanadiumPlatingLevel2/EngineeringBay', 'TerranInfantryArmorVanadiumPlatingLevel3/EngineeringBay'],
               ['ProtossAirWeaponsLevel1/CyberneticsCore', 'TerranShipWeaponsLevel1/Armory', 'zergflyerattack1'],
               ['TerranShipWeaponsLevel1/Armory', 'TerranShipWeaponsUltraCapacitorsLevel1/Armory', 'TerranShipWeaponsUltraCapacitorsLevel2/Armory', 'TerranShipWeaponsUltraCapacitorsLevel3/Armory'],
               ['ProtossAirArmorLevel1/CyberneticsCore', 'TerranShipPlatingLevel1/Armory', 'zergflyerarmor1'],
               ['TerranShipPlatingLevel1/Armory', 'TerranShipPlatingVanadiumPlatingLevel1/Armory', 'TerranShipPlatingVanadiumPlatingLevel2/Armory', 'TerranShipPlatingVanadiumPlatingLevel3/Armory'],
               ['Stim', 'StimFirebat/Firebat', 'StimFirebat/DevilDog'],
               ['Heal/Medivac', 'BonesHeal/Stetmann', 'NanoRepair/ScienceVessel', 'MedicHeal/Medic', 'MercMedicHeal/MercMedic'],
               ['CloakOnBanshee', 'RogueGhostCloak/Spectre', 'WraithCloakOn/Wraith'],
               ['CloakOff', 'WraithCloakOff/Wraith'],
               #['WeaponsFree/Ghost','SpectreWeaponsFree/Spectre'], thanks to HotS Spectre key now unbinds if set to same as HoldFire, Ghost HoldFire & weapons free toggle works correctly
               ['GhostHoldFire/Ghost', 'SpectreHoldFire/Spectre'],
               ['NukeArm/GhostAcademy', 'SpectreNukeArm/GhostAcademy'],
               ['NukeCalldown/Ghost', 'SpectreNukeCalldown/Spectre', 'HeroNukeCalldown/Nova', 'HeroNukeCalldown/Tosh', 'OdinNukeCalldown/Odin'],
               ['BunkerLoad', 'HerculesLoad/Hercules'],
               ['BunkerUnloadAll', 'HerculesUnloadAll/Hercules'],
               ['Stop','StopBunker/Bunker', 'StopPlanetaryFortress/PlanetaryFortress'],
               ['Reactor/Barracks', 'Reactor/BarracksFlying', 'Reactor/Factory', 'Reactor/FactoryFlying', 'Reactor/Starport', 'Reactor/StarportFlying'],
               ['TechLabBarracks/Barracks', 'TechLabBarracks/BarracksFlying', 'TechReactor/Barracks', 'TechReactor/BarracksFlying', 'TechLabFactory/Factory', 'BuildTechLabFactory/FactoryFlying', 'TechReactor/Factory', 'TechReactor/FactoryFlying', 'TechLabStarport/Starport', 'BuildTechLabStarport/StarportFlying', 'TechReactor/Starport', 'TechReactor/StarportFlying'],
               #['Ghost/Barracks','Spectre/Barracks'], thanks to HotS campaign these can no longer be on the same key
               #['Raven/Starport', 'BuildScienceVessel/Starport'],
               ['EMP/Ghost', 'UltrasonicPulse/Spectre'],
               ['Snipe/Ghost', 'NovaSnipe/Nova', 'Obliterate/Spectre'],
               ['Lair/Hatchery', 'Hive/Lair', 'LurkerDen/HydraliskDen', 'ImpalerDen/HydraliskDen'],
               ['MassRecall/Mothership', 'MassRecall/Artanis', 'MothershipMassRecall/Mothership', 'MothershipCoreMassRecall/MothershipCore'],
               ['Vortex/Mothership', 'Vortex/Artanis'],
               ['Mothership/Nexus', 'MothershipCore/Nexus'],
               ['AutoTurret/Raven', 'BuildAutoTurret/Raven'],
               ['PointDefenseDrone/Raven', 'BuildPointDefenseDrone/Raven'],
               ['ResearchShieldWall/BarracksTechLab', 'ResearchShieldWall/BarracksTechReactor'],
               ['Stimpack/BarracksTechLab', 'Stimpack/BarracksTechReactor'],
               ['ResearchPunisherGrenades/BarracksTechLab', 'ResearchPunisherGrenades/BarracksTechReactor', 'ResearchJackhammerConcussionGrenade/BarracksTechLab', 'ResearchJackhammerConcussionGrenade/BarracksTechReactor'],
               ['ReaperSpeed/BarracksTechLab', 'ReaperSpeed/BarracksTechReactor', 'ResearchG4Charge/BarracksTechLab', 'ResearchG4Charge/BarracksTechReactor'],
               ['ResearchIncineratorNozzles/BarracksTechLab', 'ResearchIncineratorNozzles/BarracksTechReactor'],
               ['ResearchStabilizerMedPacks/BarracksTechLab', 'ResearchStabilizerMedPacks/BarracksTechReactor'],
               ['ResearchCerberusMines/FactoryTechLab', 'ResearchCerberusMines/FactoryTechReactor'],
               ['ResearchHighCapacityBarrels/FactoryTechLab', 'ResearchHighCapacityBarrels/FactoryTechReactor'],
               ['ResearchMultiLockTargetingSystem/FactoryTechLab', 'ResearchMultiLockTargetingSystem/FactoryTechReactor'],
               ['ResearchRegenerativeBioSteel/FactoryTechLab', 'ResearchRegenerativeBioSteel/FactoryTechReactor'],
               ['ResearchStrikeCannons/FactoryTechLab', 'ResearchStrikeCannons/FactoryTechReactor'],
               ['ResearchSiegeTech/FactoryTechLab', 'ResearchSiegeTech/FactoryTechReactor', 'ResearchShapedBlast/FactoryTechLab', 'ResearchShapedBlast/FactoryTechReactor'],
               ['ResearchMedivacEnergyUpgrade/StarportTechLab', 'ResearchMedivacEnergyUpgrade/StarportTechReactor'],
               ['ResearchBansheeCloak/StarportTechLab', 'ResearchBansheeCloak/StarportTechReactor'],
               ['ResearchDurableMaterials/StarportTechLab', 'ResearchDurableMaterials/StarportTechReactor'],
               ['ResearchSeekerMissile/StarportTechLab', 'ResearchSeekerMissile/StarportTechReactor'],
               ['ResearchRavenEnergyUpgrade/StarportTechLab', 'ResearchRavenEnergyUpgrade/StarportTechReactor'],
               ['WraithCloak/StarportTechLab', 'WraithCloak/StarportTechReactor'],
               ['Baneling/Zergling', 'Baneling/Zergling2', 'Baneling/HotSRaptor', 'Baneling/HotSSwarmling', 'MorphtoHunter/HotSRaptor', 'MorphtoHunter/HotSSwarmling', 'MorphtoSplitterling/HotSRaptor', 'MorphtoSplitterling/HotSSwarmling'],
               ['DisableBuildingAttack/Baneling', 'DisableBuildingAttack/baneling', 'DisableBuildingAttack/baneling2', 'DisableBuildingAttack/HotSHunter', 'DisableBuildingAttack/HotSSplitterlingBig'],
               ['EnableBuildingAttack/Baneling', 'EnableBuildingAttack/baneling', 'EnableBuildingAttack/baneling2', 'EnableBuildingAttack/HotSHunter', 'EnableBuildingAttack/HotSSplitterlingBig'],
               ['Explode/Baneling', 'Explode/BanelingBurrowed', 'Explode/baneling', 'Explode/baneling2', 'Explode/HotSSplitterlingBig', 'Explode/HotSSplitterlingBigBurrowed', 'Explode/HotSHunter', 'Explode/HotSHunterBurrowed'],
               ['ForceField/Sentry', 'ForceField2/Sentry2'],
               ['FungalGrowth/Infestor', 'FungalGrowth/Infestor2'],
               ['GuardianShield/Sentry', 'GuardianShield/Sentry2'],
               ['Hallucination/Sentry', 'Hallucination/Sentry2'],
               ['Heal/Medivac', 'Heal/Medivac2'],
               ['InfestedTerrans/Infestor', 'InfestedTerrans/Infestor2'],
               ['NeuralParasite/Infestor', 'NeuralParasite/Infestor2', 'NPSwarm/Infestor'],
               ['Baneling/Zergling', 'Baneling/Zergling2', 'Baneling/HotSRaptor', 'Baneling/HotSSwarmling'],
               ['Apocalypse/K5Kerrigan', 'K5DropPods/K5Kerrigan', 'K5Leviathan/K5Kerrigan'],
               ['MindBolt/K5Kerrigan', 'MindBolt/KerriganGhostLab', 'PrimalSlash/K5Kerrigan'],
               ['PrimalHeal/K5Kerrigan', 'SpawnBanelings/K5Kerrigan', 'WildMutation/K5Kerrigan'],
               ['PsiStrike/K5Kerrigan', 'PsionicLift/K5Kerrigan', 'PsionicLift/KerriganGhostLab'],
               ['YamatoGun', 'SJHyperionYamato/SJHyperion', 'HyperionVoidCoopYamatoCannon/HyperionVoidCoop'],
               ['Hydralisk/Larva', 'MorphToHydraliskImpaler/Larva', 'MorphToHydraliskLurker/Larva'],
               ['Infestor/Larva', 'MorphtoDefiler/Larva'],
               ['Mutalisk/Larva', 'MorphToMutaliskBroodlord/Larva', 'MorphToMutaliskViper/Larva'],
               ['Roach/Larva', 'MorphToVile/Larva', 'MorphToCorpser/Larva'],
               ['SwarmHostMP/Larva', 'MorphToSwarmHostSplitA/Larva', 'MorphToSwarmHostSplitB/Larva'],
               ['Ultralisk/Larva', 'MorphToHotSNoxious/Larva', 'MorphToHotSTorrasque/Larva'],
               #['Viper/Larva', 'Aberration/Larva'],
               ['Zergling/Larva', 'MorphToSwarmling/Larva', 'MorphToRaptor/Larva'],
               ['LocustLaunch/SwarmHostBurrowed', 'LocustFlyingLaunch/SwarmHostSplitABurrowed', 'LocustFlyingLaunch/SwarmHostSplitARooted', 'LocustLaunch/SwarmHostRooted', 'LocustLaunchCreeper/SwarmHostSplitBBurrowed', 'LocustLaunchCreeper/SwarmHostSplitBRooted'],
               ['BurrowDown', 'BurrowHydraliskImpalerDown', 'BurrowHydraliskLurkerDown', 'ImpalerBurrowDown', 'LurkerBurrowDown'],
               ['BurrowHydraliskImpalerUp', 'BurrowHydraliskLurkerUp', 'ImpalerBurrowUp', 'LurkerBurrowUp'],  # 'SwarmHostUprootUnburrow/SwarmHostBurrowed','SwarmHostUprootUnburrow/SwarmHostSplitABurrowed','SwarmHostUprootUnburrow/SwarmHostSplitBBurrowed'
               ['BurrowDown', 'Lower/SupplyDepot'],
               #['BurrowUp', 'Raise/SupplyDepotLowered'],
               ['LurkerBurrowUp', 'Raise/SupplyDepotLowered'],
			   ['WidowMineUnburrow/WidowMine', 'Unsiege', 'LiberatorAAMode/Liberator', 'MorphToHellion/Hellion', 'AssaultMode'],
			   ['WidowMineBurrow/WidowMine', 'SiegeMode', 'MorphToHellionTank/Hellion', 'FighterMode' ],
               ['SwarmHostDeepBurrow/SwarmHostSplitB', 'SwarmHostDeepBurrow/SwarmHostSplitBBurrowed', 'SwarmHostDeepBurrow/SwarmHostSplitBRooted'],
               ['SwarmHostRoot/SwarmHost', 'SwarmHostRoot/SwarmHostSplitA', 'SwarmHostRoot/SwarmHostSplitB'],
               ['SwarmHostUproot/SwarmHostRooted', 'SwarmHostUproot/SwarmHostSplitARooted', 'SwarmHostUproot/SwarmHostSplitBRooted'],
               ['HydraliskFrenzy/Hydralisk', 'HydraliskFrenzy/HydraliskImpaler', 'HydraliskFrenzy/HydraliskLurker'],
               ['Impaler/HydraliskImpaler', 'Lurker/HydraliskLurker'],
               ['BroodLord/Corruptor', 'BroodLord/MutaliskBroodlord', 'Viper/MutaliskViper'],
               ['BlindingCloud/Viper', 'DisablingCloud/Viper'],
               ['ViperConsume/Viper', 'ViperConsumption/Viper'],
               ['BurrowChargeMP/Ultralisk', 'BurrowChargeCampaign/Ultralisk', 'BurrowChargeCampaign/HotSTorrasque', 'BurrowChargeCampaignNoxious/HotSNoxious'],
               ['Transfusion/Queen', 'Transfusion/Queen2'],
               #['Transfusion/Queen', 'Transfusion/Queen2', 'QueenBurstHeal/Queen'],
               ['GrowHugeQueen/LargeSwarmQueen', 'GrowLargeQueen/SwarmQueen', 'GrowSwarmQueen/LarvalQueen'],
               ['SwarmQueenHydralisk/HugeSwarmQueen', 'SwarmQueenHydralisk/SwarmQueenEgg', 'SwarmQueenHydraliskImpaler/HugeSwarmQueen', 'SwarmQueenHydraliskImpaler/LargeSwarmQueen', 'SwarmQueenHydraliskImpaler/SwarmQueen', 'SwarmQueenHydraliskLurker/HugeSwarmQueen', 'SwarmQueenHydraliskLurker/LargeSwarmQueen', 'SwarmQueenHydraliskLurker/SwarmQueen'],
               ['ParasiticInvasion/LarvalQueen', 'SwarmQueenParasiticInvasion/HugeSwarmQueen', 'SwarmQueenParasiticInvasion/LargeSwarmQueen', 'SwarmQueenParasiticInvasion/SwarmQueen'],
               ['SwarmQueenCorpser/LargeSwarmQueen', 'SwarmQueenCorpser/HugeSwarmQueen', 'SwarmQueenCorpser/SwarmQueen', 'SwarmQueenRoach/HugeSwarmQueen', 'SwarmQueenRoach/LargeSwarmQueen', 'SwarmQueenRoach/SwarmQueenEgg', 'SwarmQueenVile/HugeSwarmQueen', 'SwarmQueenVile/LargeSwarmQueen', 'SwarmQueenVile/SwarmQueen'],
               ['SwarmQueenRaptor/HugeSwarmQueen', 'SwarmQueenRaptor/LargeSwarmQueen', 'SwarmQueenRaptor/SwarmQueen', 'SwarmQueenSwarmling/HugeSwarmQueen', 'SwarmQueenSwarmling/LargeSwarmQueen', 'SwarmQueenSwarmling/SwarmQueen', 'SwarmQueenZergling/HugeSwarmQueen', 'SwarmQueenZergling/LargeSwarmQueen', 'SwarmQueenZergling/SwarmQueen', 'SwarmQueenZergling/SwarmQueenEgg'],
               ['GreaterSpire/Spire', 'GreaterSpireBroodlord/Spire'],
               ['RespawnZergling/Hatchery', 'RespawnZergling/Hive', 'RespawnZergling/Lair'],
               #['GenerateCreep/Overlord','StopGenerateCreep/Overlord']]
               ['VoidSentryShieldRepair/Sentry', 'VoidSentryShieldRepairDouble/SentryAiur'],
               ['UpgradeToWarpGate/Gateway', 'UpgradeToRoboticsFacilityWarp/RoboticsFacility', 'UpgradeToStargateWarp/Stargate'],
               ['MorphBackToGateway/WarpGate', 'MorphBackToRoboticsFacility/RoboticsFacilityWarp', 'MorphBackToStargate/StargateWarp'],
               ['Vortex/Mothership', 'Vortex/Artanis', 'VoidSentryBlackHole/SOAMothershipv4', 'TemporalField/Mothership', 'TemporalField/MothershipCore'],
               ['250mmStrikeCannons/Thor', '250mmStrikeCannons/ThorWreckageSwann'],
               ['SelfRepair/Thor', 'SelfRepair/ThorWreckageSwann'],
               ['Salvage/Bunker', 'Salvage/MissileTurret', 'Salvage/KelMorianGrenadeTurret', 'Salvage/PerditionTurret', 'Salvage/KelMorianMissileTurret'],
               ['Hyperjump/Battlecruiser', 'HyperionVoidCoopHyperjump/HyperionVoidCoop', 'HyperjumpHercules/Hercules'],
               ['Charge/Zealot', 'Charge/ZealotAiur', 'Charge/ZealotPurifier', 'VoidZealotShadowCharge/ZealotShakuras', 'Charge/ShadowOfTheVoidZealot'],
               ['ResearchIncineratorGauntlets/BarracksTechLab', 'ResearchIncineratorGauntlets/BarracksTechReactor'],
               ['ResearchJuggernautPlating/BarracksTechLab', 'ResearchJuggernautPlating/BarracksTechReactor'], ['ResearchStabilizerMedpacks/BarracksTechLab', 'ResearchStabilizerMedpacks/BarracksTechReactor'],
               ['ResearchHellbatHellArmor/FactoryTechLab', 'ResearchHellbatHellArmor/FactoryTechReactor'],
               ['ResearchAresClassTargetingSystem/FactoryTechLab', 'ResearchAresClassTargetingSystem/FactoryTechReactor'],
               ['ResearchMultiLockWeaponsSystem/FactoryTechLab', 'ResearchMultiLockWeaponsSystem/FactoryTechReactor'],
               ['ResearchMaelstromRounds/FactoryTechLab', 'ResearchMaelstromRounds/FactoryTechReactor'],
               ['ResearchLockOnRangeUpgrade/FactoryTechLab', 'ResearchLockOnRangeUpgrade/FactoryTechReactor'],
               ['ResearchCycloneLockOnDamageUpgrade/FactoryTechLab', 'ResearchCycloneLockOnDamageUpgrade/FactoryTechReactor'],
               ['Research330mmBarrageCannon/FactoryTechLab', 'Research330mmBarrageCannon/FactoryTechReactor'],
               ['ResearchShockwaveMissileBattery/StarportTechLab', 'ResearchShockwaveMissileBattery/StarportTechReactor'],
               ['ResearchPhobosClassWeaponsSystem/StarportTechLab', 'ResearchPhobosClassWeaponsSystem/StarportTechReactor'],
               ['ResearchRipwaveMissiles/StarportTechLab', 'ResearchRipwaveMissiles/StarportTechReactor'],
               ['SummonNydusWorm/NydusNetwork', 'ZagaraVoidCoopNydusWorm/NydusNetwork'],
               ['Queen', 'QueenCoop'],
               ['BuildCreepTumor/Queen', 'BuildCreepTumor/QueenCoop'],
               ['MorphMorphalisk/Queen', 'MorphMorphalisk/QueenCoop'],
               ['Transfusion/Queen', 'Transfusion/QueenCoop'],
               ['Immortal/RoboticsFacility', 'Immortal/RoboticsFacilityWarp'],
               ['Colossus/RoboticsFacility', 'Colossus/RoboticsFacilityWarp'],
               ['Observer/RoboticsFacility', 'Observer/RoboticsFacilityWarp']]
